export const INIT_STATES="STATES.INIT_STATES";
export const VIEW_STATE="STATES.VIEW_STATE";
export const EDIT_STATE="STATES.EDIT_STATE";
export const LOADING="STATES.LOADING";
export const ERROR="STATES.ERROR";